### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by hudafauzanm** [2019-pemrogramanberbasiskerangkakerja-g/sistem-kehadiran-online-vicky-aan-abid#1]
Untuk saat ini belum adakah link buat aksesnya? terima kasih

**Comment by hudafauzanm** [comment]
Apakah ini sudah di deploy ? ini sudah mendekati deadline pengumpulan dan belum bisa diakses

**Comment by aanramadhan** [comment]
sistem dapat diakses di http://pbkk4.web.id/auth
