### ISSUE TITLE
api tambah matkul

### ISSUE THREAD

**Issue by fzulfa** [2019-pemrogramanberbasiskerangkakerja-g/sistem-kehadiran-online-vicky-aan-abid#5]
/tambahmatkul belum berhasil insert ke database karena id_matkul tidak terbaca. (harusnya auto increment)

**Comment by vickymahfudy** [comment]
> /tambahmatkul belum berhasil insert ke database karena id_matkul tidak terbaca. (harusnya auto increment)

idmatkul tidak autoincrement, kami asumsikan idmatkul bisa digenerate pada saat tambah matkul, namun api kami memang belum lengkap
